[project]
name = "zarr-multiscale"
version = "0.1.0"
description = ""
authors = ["Yurii Zubov <zubov452@gmail.com>"]
readme = "README.md"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "3.11.*"
bokeh = ">=3.3.2"
numpy = ">=1.26.2"
zarr = ">=2.18.3,<3.0"
dask = ">=2023.12.0"
numcodecs = ">=0.15.1,<0.16.1"
click = ">=8.1.8,<9.0.0"
scipy = ">=1.16.1"

[pypi-dependencies]
xarray-multiscale = ">=2.1.0"
dask-jobqueue = "==0.8.2"

[tasks]
help = "python src/to_multiscale.py --help"
