[project]
name = "zarr-multiscale"
version = "0.1.0"
description = ""
authors = ["Yurii Zubov <zubov452@gmail.com>"]
readme = "README.md"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "3.11.*"
bokeh = ">=3.3.2"
numpy = ">=1.26.2"
zarr = ">=2.18.3"
dask = ">=2023.12.0"
numcodecs = ">=0.15.1"
numba = ">=0.59.0"
click = "*"
scipy = "*"

[pypi-dependencies]
xarray-multiscale = ">=2.1.0"
dask-jobqueue = "==0.8.2"

[tasks]
help = "python src/to_multiscale.py --help"
